"""Initial migration.

Revision ID: 17cf1226df13
Revises: 
Create Date: 2024-08-19 07:36:30.883150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cf1226df13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dna_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dna_sequence')
    # ### end Alembic commands ###
